name: build and push and deploy
on:
  push:
    branches:
    - env-test

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & Push
    runs-on:
      -self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: uruchom Å›rodowisko docker-compose
        run: |
          docker-compose -f ./docker-compose/docker-compose-prge-local.yaml --env-file .env -p local -prge up --build -d